//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boqtakeoff.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("boqtakeoff.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.XEUW44N220PKJBW2NBZ6X65B9K6WWR.
        /// </summary>
        internal static string _client_id {
            get {
                return ResourceManager.GetString("_client_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c226868a95ae747cc7cd3966b8c69e2e6d6998fcf6.
        /// </summary>
        internal static string _client_secret {
            get {
                return ResourceManager.GetString("_client_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://creator.zoho.in/api/v2/bigfish.central/purchases/form/CreateBOQ_RevitPlugin.
        /// </summary>
        internal static string _create_boq_url {
            get {
                return ResourceManager.GetString("_create_boq_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://creator.zoho.in/api/v2/bigfish.central/purchases/report/RevitBOQDataValidationErrors_Report.
        /// </summary>
        internal static string _get_bf_error_log_url {
            get {
                return ResourceManager.GetString("_get_bf_error_log_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://creator.zoho.in/api/v2/bigfish.central/purchases/report/CreateBOQ_RevitPlugin_Report.
        /// </summary>
        internal static string _get_boq_version_details_url {
            get {
                return ResourceManager.GetString("_get_boq_version_details_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://creator.zoho.in/api/v2/bigfish.central/packages/report/All_Project_Details.
        /// </summary>
        internal static string _get_project_uid_url {
            get {
                return ResourceManager.GetString("_get_project_uid_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.1ee3195f4d06fe07e54c18dd331fed75.60e5a61e7831d25ca6847e469d7e6500.
        /// </summary>
        internal static string _refresh_token {
            get {
                return ResourceManager.GetString("_refresh_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://accounts.zoho.in/oauth/v2/token.
        /// </summary>
        internal static string _token_url {
            get {
                return ResourceManager.GetString("_token_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigFish_Title {
            get {
                object obj = ResourceManager.GetObject("BigFish Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Breadcrumb_Step2 {
            get {
                object obj = ResourceManager.GetObject("Breadcrumb_Step2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Breadcrumb_Step3 {
            get {
                object obj = ResourceManager.GetObject("Breadcrumb_Step3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Breadcrumb_Step4 {
            get {
                object obj = ResourceManager.GetObject("Breadcrumb_Step4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn1 {
            get {
                object obj = ResourceManager.GetObject("btn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn11 {
            get {
                object obj = ResourceManager.GetObject("btn11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn2 {
            get {
                object obj = ResourceManager.GetObject("btn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn21 {
            get {
                object obj = ResourceManager.GetObject("btn21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads\BOQ Template.xlsx.
        /// </summary>
        internal static string DownloadFolder {
            get {
                return ResourceManager.GetString("DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        internal static string DownloadTemplateTitle {
            get {
                return ResourceManager.GetString("DownloadTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall,Roof,Floor,Mechanical Equipment,Interior Design.
        /// </summary>
        internal static string FamilyCategories {
            get {
                return ResourceManager.GetString("FamilyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Files (*.csv, *.xls, *,xlsx)|*.csv;*.xls;*.xls*|All files (*.*)|*.*.
        /// </summary>
        internal static string FileTypes {
            get {
                return ResourceManager.GetString("FileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string LoggerFolderPath {
            get {
                return ResourceManager.GetString("LoggerFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOQ Extractor.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bigfish Color Scheme.
        /// </summary>
        internal static string NewColorSchemeName {
            get {
                return ResourceManager.GetString("NewColorSchemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P2_Stage1 {
            get {
                object obj = ResourceManager.GetObject("P2-Stage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P2_Stage11 {
            get {
                object obj = ResourceManager.GetObject("P2-Stage11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 138,231,90:167,180,176:202,80,172:42,60,114:66,68,178:56,194,150:106,112,215:165,63,141:114,96,141:162,197,175:112,223,58:123,232,70:199,129,154:136,139,175:138,62,214:71,62,63:164,157,195:207,236,120:196,215,203:158,117,127:75,103,112:206,169,70:95,183,68:148,89,109:205,212,195:79,89,50:136,107,81:117,243,86:189,141,208:147,165,66:76,103,61:67,126,82:102,170,122:184,218,108:204,76,112:126,61,72:134,186,165:193,84,58:86,199,91:66,77,75:71,188,65:42,138,206:88,210,128:152,219,145:138,192,118:182,150,203:183, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomColorScheme {
            get {
                return ResourceManager.GetString("RoomColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room1:255,210,244-Room2:215,210,234-Room3:115,210,244-Room4:5,210,76.
        /// </summary>
        internal static string RoomNamesAsLegendAndColor {
            get {
                return ResourceManager.GetString("RoomNamesAsLegendAndColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bigfish-Room.
        /// </summary>
        internal static string RoomPattern {
            get {
                return ResourceManager.GetString("RoomPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Interior - Floor, Interior - Partition, Interior - Ceiling, Interior - Door, Interior - Speciality Equipment, Interior - Glass Partition, Interior - Furniture, Interior - Profile &amp; Generic Elements, Interior - Lintels, Interior - Joinery, MEP - Duct, MEP - Duct Fitting, MEP - HVAC, MEP - Mechanical Equipment, MEP - Fire Pipe, MEP - Sprinkler, MEP - Fire Alarm, MEP - Electrical Fixture, MEP - Lighting Fixture, MEP - Communication Device, MEP - Cable Tray.
        /// </summary>
        internal static string StaggeredGridData {
            get {
                return ResourceManager.GetString("StaggeredGridData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step_one {
            get {
                object obj = ResourceManager.GetObject("step-one", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step_three {
            get {
                object obj = ResourceManager.GetObject("step-three", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step_two {
            get {
                object obj = ResourceManager.GetObject("step-two", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file (csv/excel).
        /// </summary>
        internal static string Step1_select_file_label {
            get {
                return ResourceManager.GetString("Step1_select_file_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select files.
        /// </summary>
        internal static string Step1_SelectFile_empty_Message {
            get {
                return ResourceManager.GetString("Step1_SelectFile_empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Step11 {
            get {
                object obj = ResourceManager.GetObject("Step11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project.
        /// </summary>
        internal static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Project.
        /// </summary>
        internal static string Step2_Empty_Project_Message {
            get {
                return ResourceManager.GetString("Step2_Empty_Project_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project Name.
        /// </summary>
        internal static string Step2_select_project_label {
            get {
                return ResourceManager.GetString("Step2_select_project_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Version.
        /// </summary>
        internal static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Version Label.
        /// </summary>
        internal static string Step3_empty_version_lable {
            get {
                return ResourceManager.GetString("Step3_empty_version_lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Label.
        /// </summary>
        internal static string Step3_select_version_label {
            get {
                return ResourceManager.GetString("Step3_select_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
    }
}
